project:
  type: website

website:
  title: "DSAN-5000"
  favicon: "images/2023-09-06-23-12-12.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About me
      - text: "Slides"
        menu: 
          - text: "Week-01"
            href:  about.ipynb
          - text: "Week-02"
            href:  about.ipynb

format:
  html:
    theme: sandstone
    toc: true



